# Generated by Django 5.0.2 on 2024-06-24 11:42

import django.db.models.deletion
import django.views.generic.list
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryListView',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.post')),
            ],
            bases=(django.views.generic.list.ListView, 'blog.post'),
        ),
    ]
